import 'package:flutter/material.dart';
import 'header_footer.dart';
import 'app_style.dart';

class TermsPage extends StatelessWidget {
  const TermsPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SingleChildScrollView(
        child: Container(
          color: AppColors.background, // green background
          child: Center(
            child: ConstrainedBox(
              constraints: const BoxConstraints(maxWidth: 1000),
              child: Column(
                children: [
                  const Header(), // header already has white background inside
                  AppContainer(
                    color: AppColors.white,
                    padding: const EdgeInsets.all(16),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text('Terms of Use', style: AppTextStyles.h1),
                        const SizedBox(height: 16),
                        Text(
                          'Effective from February 10, 2026\nLast Updated: February 10, 2026',
                          style: AppTextStyles.paragraph,
                        ),
                        const SizedBox(height: 16),
                        Text(
                          'Welcome to Farming Tips, a service provided by Design 86 LLC ("Company," "we," "us," or "our"). '
                          'By accessing or using our mobile application and website, you agree to comply with and be bound by the following terms. '
                          'If you do not agree, please do not use our services.',
                          style: AppTextStyles.paragraph,
                        ),
                        const SizedBox(height: 16),
                        Text('1. The Service', style: AppTextStyles.h2),
                        Text(
                          'Farming Tips is a platform designed to share agricultural knowledge. The application is free to use and intended for a global audience, with a primary focus on the farming community in Kenya. We reserve the right to modify or discontinue any part of the service at any time without notice.',
                          style: AppTextStyles.paragraph,
                        ),
                        const SizedBox(height: 12),
                        Text(
                          '2. User Roles and Content',
                          style: AppTextStyles.h2,
                        ),
                        Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              '• General Users: Access to the app is "Read-Only." Users can view crop data, descriptions, and images provided by administrators.',
                              style: AppTextStyles.paragraph,
                            ),
                            Text(
                              '• Admins: Administrators are the sole creators of content on the platform. Admins are responsible for the accuracy and legality of the names, descriptions, and images they upload.',
                              style: AppTextStyles.paragraph,
                            ),
                          ],
                        ),
                        const SizedBox(height: 12),
                        Text(
                          '3. Disclaimer of Liability (The "Farmer\'s Disclaimer")',
                          style: AppTextStyles.h2,
                        ),
                        Text(
                          'Use at Your Own Risk: All farming tips, guides, and crop information provided in this app are user-generated by Admins. Design 86 LLC does not verify, vet, or guarantee the accuracy, completeness, or safety of any tip provided.',
                          style: AppTextStyles.paragraph,
                        ),
                        Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              '• Crop failure or reduced yields.',
                              style: AppTextStyles.paragraph,
                            ),
                            Text(
                              '• Financial loss resulting from following advice in the app.',
                              style: AppTextStyles.paragraph,
                            ),
                            Text(
                              '• Damage to property or livestock.',
                              style: AppTextStyles.paragraph,
                            ),
                            Text(
                              '• Incorrect identification of pests, diseases, or plants.',
                              style: AppTextStyles.paragraph,
                            ),
                          ],
                        ),
                        const SizedBox(height: 12),
                        Text(
                          '4. Intellectual Property and Scraping',
                          style: AppTextStyles.h2,
                        ),
                        Text(
                          'At Design 86 LLC, we believe in the open sharing of knowledge. We do not claim intellectual property (IP) rights over the crop descriptions or images uploaded by Admins. Users are permitted to save, share, or scrape data from the application for educational or personal use. However, the "Farming Tips" brand name and app design remain the property of Design 86 LLC.',
                          style: AppTextStyles.paragraph,
                        ),
                        const SizedBox(height: 12),
                        Text('5. Weather Data', style: AppTextStyles.h2),
                        Text(
                          'The app provides weather information via third-party APIs. We do not guarantee the accuracy of these forecasts. Weather data is provided for convenience only and should not be relied upon for life-safety decisions or critical farm planning.',
                          style: AppTextStyles.paragraph,
                        ),
                        const SizedBox(height: 12),
                        Text('6. Account Eligibility', style: AppTextStyles.h2),
                        Text(
                          'Our services are intended for users aged 18 and older. By creating an account, you represent that you meet this age requirement. You are responsible for maintaining the confidentiality of your email and password login credentials.',
                          style: AppTextStyles.paragraph,
                        ),
                        const SizedBox(height: 12),
                        Text('7. Fees', style: AppTextStyles.h2),
                        Text(
                          'Farming Tips is currently 100% free to use. While we may introduce features or support the app via other means in the future, the current core functionality is provided at no cost to the user.',
                          style: AppTextStyles.paragraph,
                        ),
                        const SizedBox(height: 12),
                        Text('8. Termination', style: AppTextStyles.h2),
                        Text(
                          'We reserve the right to suspend or terminate accounts that violate these terms or engage in behavior that threatens the security of our platform or other users. You may delete your account at any time by contacting us.',
                          style: AppTextStyles.paragraph,
                        ),
                        const SizedBox(height: 12),
                        Text('9. Governing Law', style: AppTextStyles.h2),
                        Text(
                          'These Terms shall be governed by and construed in accordance with the laws of the State of California, United States, without regard to its conflict of law provisions.',
                          style: AppTextStyles.paragraph,
                        ),
                        const SizedBox(height: 12),
                        Text('10. Contact Us', style: AppTextStyles.h2),
                        Text(
                          'If you have any questions regarding these Terms, please contact us at:\nDesign 86 LLC\nEmail: info@d86.us',
                          style: AppTextStyles.paragraph,
                        ),
                      ],
                    ),
                  ),
                  const Footer(),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
